### ISSUE TITLE
Swift package manager support

### ISSUE THREAD

**Issue by tottakai** [wingify/vwo-ios-sdk#13]
Hi,
i would be nice to finally add Swift package manager support to the iOS SDK. Any timeline on that?

**Comment by agusmarkosich8** [comment]
Hello +1 to @tottakai comment, any updates?

**Comment by manuelescrig-ifolor** [comment]
Same here. Any updates on this?

**Comment by softvar** [comment]
We are glad to announce that swift package manager is now supported.

**Comment by agusmarkosich8** [comment]
hello @softvar when I try to use it I receive the message "No such module VWO". Do you have an example of using the package working?
Regards

**Comment by AdamCockingHX** [comment]
Hey @agusmarkosich8 not sure if you are still seeing this issue, but I had the same thing and found the library was not being added to the build phase automatically. So if you go to Project -> Build Phases -> Link Binary With Libraries, and add it there, rebuilding the project will then fix this issue
