### ISSUE TITLE
Framework files

### ISSUE THREAD

**Issue by eneskaya** [wingify/vwo-ios-sdk#2]
Hi, In your tutorial (https://vwo.com/knowledge/integrating-ios-sdk/) You claim, that I can download a libVWO.a and VWO.h file, but when I download the latest release there is no libVWO.a

We are trying to write a cordova plugin for vwo and thus I need the libVWO.a

Could you provide this? Thanks

**Comment by swapnilagarwwal** [comment]
@eneskaya earlier we used to provide .h and .a files, but since we have open sourced our SDK, we directly provide the .h and .m files.
I will update the documentation.
Sorry for the trouble.
