### ISSUE TITLE
pendingMessage is always nil

### ISSUE THREAD

**Issue by swapnilagarwwal** [wingify/vwo-ios-sdk#4]
pendingMesssage is nil, because of this messages are not getting added into this.

I believe this is happening because:
_pendingMessages = [NSMutableArray arrayWithContentsOfURL:VAOFile.messagesPath];

arrayWithContentsOfURL:
returns an array containing the contents specified by aURL. Returns nil if the location can’t be opened or if the contents of the location can’t be parsed into an array.

https://github.com/wingify/vwo-ios-sdk/blob/3323ba594aef6dac127f2e6f41c3adccc10023b5/vwo-sdk/VAOAPIClient.m#L45

**Comment by kaunteya** [comment]
Fixed in 2.0.0-beta4
