### ISSUE TITLE
User not becoming part of control

### ISSUE THREAD

**Issue by swapnilagarwwal** [wingify/vwo-ios-sdk#5]
I think we need to remove this line. Because of this line user is not becoming part of control, when control has all the keys.

https://github.com/wingify/vwo-ios-sdk/blob/3323ba594aef6dac127f2e6f41c3adccc10023b5/vwo-sdk/Models/VAOCampaign.m#L85

**Comment by kaunteya** [comment]
Fixed in 2.0.0-beta4
