### ISSUE TITLE
String Format for logging making the app to crash.

### ISSUE THREAD

**Issue by nmiyasato** [wingify/vwo-ios-sdk#6]
- (void) markConversionForGoalId:(NSInteger)goalId
                    experimentId:(NSInteger)experimentId
                     variationId:(NSInteger)variationId
                         revenue:(NSNumber *)revenue {

        VAOLogInfo(@"Mark Goal conversion '%@' in campaign '%@'", goalId, experimentId);

crashes due to %@ when it should be %d

**Comment by kaunteya** [comment]
Fixed in 2.0.0-beta4
